function currentPlan(d){
  const mode=state.settings?.mode||'count',remaining=allRemainingFocusIds().length;
  const review=d&&remainingDailyQuestions(d).length===0,available=review?focusQuestionIds(d).length:(remaining||FOCUS_TOTAL);
  const requested=mode==='time'?Math.max(20,Math.round((state.settings.minutes||DEFAULT_FOCUS_MINUTES)/2)):(state.settings.count==='all'?available:Math.max(20,Number(state.settings.count)||DEFAULT_FOCUS_COUNT));
  const count=Math.min(available,requested);return {mode,total:available,count,label:`${count}문항 · ${review?'완료 범위 복습':'오늘 목표'}`,detail:count<20?'마지막 남은 문항':'기본 40문항'};
}
function requestFocus(id){
  const active=state.activeDaily,ds=state.daily[active];
  const resumable=focusRunActive()&&ds?.queue?.length&&!ds.sessionDone&&ds.index<ds.queue.length;
  const target=resumable?active:(DAILIES.some(d=>d.id===id)?id:(nextDaily()?.id||DAILIES[0].id));
  if(focusRunActive()||focusGateReady()){state.activeDaily=target;state.view='dailyIntro';save();render();return;}startQuick(false,target);
}
function nextQuick(){const s=state.quick;if(state.view!=='quick'||!s||s.done||!s.answered||!s.answers?.[s.index])return;s.index++;s.answered=false;s.pick=null;s.detail='';if(s.index>=s.queue.length&&s.answers.length===QUICK_REQUIRED_COUNT){s.done=true;state.focusGate={ready:true,completedAt:new Date().toISOString(),pendingDailyId:state.focusGate?.pendingDailyId||nextDaily()?.id||null};}save();render();}
function weakQuestionIds(pool=QUESTIONS){return pool.filter(q=>{const s=qstat(q.id);return s.attempts>0&&(s.lastCorrect===false||['again','hard'].includes(s.lastRating));}).sort((a,b)=>{const A=qstat(a.id),B=qstat(b.id);return (B.lastCorrect===false?10:0)+(B.lastRating==='again'?5:0)-((A.lastCorrect===false?10:0)+(A.lastRating==='again'?5:0));}).map(q=>q.id);}
function conceptStatus(cid){const qs=QUESTIONS.filter(q=>q.concept===cid),seen=qs.filter(q=>qstat(q.id).attempts>0);if(!seen.length)return 'UNSEEN';if(state.reviewBank[cid]?.status&&state.reviewBank[cid].status!=='MASTERED')return 'REVIEW_DUE';if(seen.some(q=>qstat(q.id).lastCorrect===false||['again','hard'].includes(qstat(q.id).lastRating)))return 'REVIEW_DUE';if(seen.length<qs.length)return 'LEARNING';return qs.length>=2&&seen.every(q=>qstat(q.id).lastCorrect===true&&['good','easy'].includes(qstat(q.id).lastRating))?'STABLE':'EXPOSED';}
function reviewDueEntries(){const today=localDayKey();return reviewEntries().filter(e=>e.status!=='MASTERED'&&e.dueOn<=today).sort((a,b)=>String(a.dueOn).localeCompare(String(b.dueOn))||(b.wrongCount||0)-(a.wrongCount||0));}
function reviewVariant(e,used,pool=QUICK_SET){const ids=conceptQids(e.concept).filter(id=>pool.has(id)&&!used.has(id));const alternatives=ids.filter(id=>id!==e.lastWrongQid&&id!==e.lastServedQid);return alternatives.find(id=>!(e.correctQids||[]).includes(id)&&qstat(id).attempts===0)||alternatives.find(id=>!(e.correctQids||[]).includes(id))||alternatives[0]||ids.find(id=>id!==e.lastServedQid)||ids[0]||null;}
function buildQuickRecoveryQueue(count=QUICK_REQUIRED_COUNT){
  count=integer(count,1,QUICK_REQUIRED_COUNT,QUICK_REQUIRED_COUNT);const used=new Set(),recovery=[],base=[];
  for(const e of reviewDueEntries()){if(recovery.length>=Math.min(6,count))break;const id=reviewVariant(e,used,QUICK_SET);if(!id)continue;used.add(id);recovery.push(id);e.lastServedQid=id;e.lastServedAt=new Date().toISOString();}
  const valid=validQuickIds(),weak=weakQuestionIds(quickQuestions()),unseen=valid.filter(id=>qstat(id).attempts===0),seen=valid.slice().sort((a,b)=>qstat(a).attempts-qstat(b).attempts);
  for(const id of weak.concat(unseen,seen,valid)){if(used.size>=count)break;if(!used.has(id)){used.add(id);base.push(id);}}return {queue:recovery.concat(base),recoveryIds:recovery};
}
function ensureStudyDay(){const today=localDayKey();if(state.studyDate===today)return;state.studyDate=today;state.quick=null;state.focusGate={ready:false,pendingDailyId:null,completedAt:null};state.focusRun=null;for(const ds of Object.values(state.daily)){ds.queue=[];ds.index=0;ds.sessionDone=true;ds.answered=false;ds.pick=null;ds.repeats={};}if(['quick','dailyIntro','learn','dailyEnd','sessionEnd'].includes(state.view))state.view='home';save();}
function focusRecoveryQueue(d,baseIds){const pool=new Set(focusQuestionIds(d)),used=new Set(),extras=[],marked=new Set();for(const e of reviewDueEntries()){if(marked.size+extras.length>=6)break;const id=reviewVariant(e,used,pool);if(!id)continue;used.add(id);e.lastServedQid=id;if(baseIds.includes(id))marked.add(id);else extras.push({qid:id,isReview:true,recovery:true,repeat:false});}return extras.concat(baseIds.map(qid=>({qid,isReview:false,recovery:marked.has(qid),repeat:false})));}
function startDaily(id){
  const d=dailyById(id);if(!d)return;
  if(!focusRunActive()){if(!focusGateReady()){requestFocus(id);return;}const plan=currentPlan(d),review=remainingDailyQuestions(d).length===0;state.focusRun={active:true,target:Math.max(1,plan.count),done:0,mode:review?'review':'learn',completedQids:[],startedAt:new Date().toISOString(),startDailyId:id};state.focusGate={ready:false,pendingDailyId:null,completedAt:state.focusGate?.completedAt||null};}
  const st=state.daily[id]||{done:[],completed:false,startCoverage:firstCoverage()};
  if(st.queue?.length&&!st.sessionDone&&st.index<st.queue.length){state.daily[id]=st;state.activeDaily=id;state.view='learn';save();render();return;}
  const baseIds=state.focusRun.mode==='review'?focusQuestionIds(d).slice(0,focusRunRemaining()):dailyCoreQuestions(d);
  if(!baseIds.length){state.daily[id]=st;state.activeDaily=id;state.view='dailyEnd';save();render();return;}
  const queue=state.focusRun.mode==='review'?baseIds.map(qid=>({qid,isReview:false,repeat:false})):focusRecoveryQueue(d,baseIds);
  Object.assign(st,{queue,baseCount:baseIds.length,index:0,answered:false,pick:null,sessionDone:false,repeats:{},plan:{...state.settings}});state.daily[id]=st;state.view='learn';state.activeDaily=id;save();render();
}
function answerQuick(pick){const s=state.quick,q=quickCurrent();if(state.view!=='quick'||!s||!q||s.done||s.answered||!validPick(pick))return;s.answered=true;s.pick=pick;const st=qstat(q.id),ok=pick===q.answer;st.attempts++;if(ok)st.correct++;st.lastCorrect=ok;st.lastRating=ok?'good':'again';st.lastPick=pick;st.lastAttemptAt=new Date().toISOString();state.questionStats[q.id]=st;if(ok&&state.reviewBank[q.concept])settleReview(q.id);else if(!ok)registerWrong(q.id,quickIsRecovery(q.id)?'review':'quick',pick);s.answers[s.index]={qid:q.id,pick,ok,recovery:quickIsRecovery(q.id)};save();render();}
function answerLearn(pick){const d=dailyById(state.activeDaily),s=d&&state.daily[d.id],item=s?.queue?.[s.index];if(state.view!=='learn'||!item||s.answered||s.sessionDone||!validPick(pick))return;const q=questionById(item.qid);if(!q)return;s.answered=true;s.pick=pick;const st=qstat(q.id),ok=pick===q.answer;st.attempts++;if(ok)st.correct++;st.lastCorrect=ok;st.lastPick=pick;st.lastAttemptAt=new Date().toISOString();if(!ok){st.lastRating='again';registerWrong(q.id,'focus',pick);}state.questionStats[q.id]=st;save();render();requestAnimationFrame(()=>{if(state.view!=='learn'||state.activeDaily!==d.id||state.daily[d.id]?.queue?.[state.daily[d.id].index]?.qid!==q.id||!state.daily[d.id].answered)return;const e=$('.exp');if(e)e.scrollIntoView({behavior:'auto',block:'start'});});}
function rateLearn(rate){
  const d=dailyById(state.activeDaily),s=d&&state.daily[d.id],item=s?.queue?.[s.index];if(state.view!=='learn'||!item||!s.answered||!['again','hard','good','easy'].includes(rate))return;
  const q=questionById(item.qid),st=qstat(item.qid),ok=s.pick===q.answer;st.lastRating=ok?rate:'again';state.questionStats[q.id]=st;if(ok&&['good','easy'].includes(rate))settleReview(q.id);if(ok&&['again','hard'].includes(rate))registerWeak(q.id,'self');
  const first=!item.isReview&&!(s.done||[]).includes(q.id);if(first)s.done=(s.done||[]).concat(q.id);
  if(focusRunActive()){const run=state.focusRun;run.completedQids=run.completedQids||[];const counted=run.mode==='review'?!item.isReview&&!run.completedQids.includes(q.id):first;if(counted){run.done=Math.min(run.target,run.done+1);run.completedQids.push(q.id);}}
  s.repeats=s.repeats||{};if(['again','hard'].includes(rate)&&!s.repeats[q.id]){s.repeats[q.id]=1;s.queue.splice(Math.min(s.index+(rate==='again'?3:6),s.queue.length),0,{qid:q.id,isReview:true,repeat:true});}
  s.index++;s.answered=false;s.pick=null;if(s.index>=s.queue.length){s.sessionDone=true;s.completed=focusQuestionIds(d).every(qid=>(s.done||[]).includes(qid));if(focusRunActive()&&state.focusRun.done>=state.focusRun.target){state.focusRun.active=false;state.focusRun.completedAt=new Date().toISOString();}if(s.completed)s.endCoverage=firstCoverage();state.view=s.completed?'dailyEnd':'sessionEnd';}save();render();
}
function finalizeMockResults(){const m=state.mock;if(!m||m.reviewRecorded||!Array.isArray(m.answers)||m.answers.length!==MOCK.length||!m.answers.every(validPick))return false;MOCK.forEach((q,i)=>{const pick=m.answers[i],st=qstat(q.id),ok=pick===q.answer;st.attempts++;if(ok)st.correct++;st.lastCorrect=ok;st.lastRating=ok?'good':'again';st.lastPick=pick;st.lastAttemptAt=new Date().toISOString();state.questionStats[q.id]=st;if(!ok)registerWrong(q.id,'mock',pick);});m.reviewRecorded=true;return true;}
function advanceMock(){const m=state.mock;if(state.view!=='mock'||!m||m.submitted||!validPick(m.answers[m.index]))return;if(m.index<MOCK.length-1)m.index++;else if(m.answers.every(validPick)){finalizeMockResults();m.submitted=true;m.reviewIndex=0;}else m.index=m.answers.findIndex(x=>!validPick(x));save();render();}
