function completedHomeView(){return shell(`${chrome('새마을금고 학습')}<div class="learn-hub"><section class="learn-card"><h2>오늘 학습을 완료했습니다.</h2><p>1단계 10문항 · 2단계 ${state.focusRun.done}문항</p><p>Daily ${DAILIES.filter(d=>state.daily[d.id]?.completed).length}/${DAILIES.length} 완료 · 미학습 집중문항 ${allRemainingFocusIds().length}개</p><button class="wide" data-additional>추가 학습 · 새 10문항부터</button><div class="learn-actions"><button data-nav="map">범위별 진행상태</button><button data-nav="tools">기록·백업</button></div></section><section class="learn-card"><h3>복습 안내</h3><p>취약 개념은 오답 기록에 남습니다. 전용 문제군에 맞추어 5분 문제 또는 집중학습에서 다시 확인합니다.</p></section></div>`,'home');}
function dailyIntroView(id){
 const d=dailyById(id);if(!d)return learnHubView();
 if(!focusGateReady()&&!focusRunActive())return shell(`${chrome('집중학습 잠김',{back:true})}<div class="learn-hub"><section class="learn-card"><h2>먼저 5분 문제 10문항을 완료하세요.</h2><button class="wide" data-start-quick>1단계 시작</button></section></div>`,'learn');
 const ds=state.daily[id]||{},run=state.focusRun,plan=currentPlan(d),review=focusRunActive()?run.mode==='review':ds.completed===true;
 const target=focusRunActive()?run.target:plan.count,done=focusRunActive()?run.done:0,resume=ds.queue?.length&&!ds.sessionDone&&ds.index<ds.queue.length;
 return shell(`${chrome('2단계 · 집중학습',{back:true,right:d.id})}<div class="body"><section class="hero"><span class="kicker">STEP 2</span><h2>${esc(d.title)}</h2><p>${esc(d.subtitle)}</p></section><section class="card"><h3>오늘 ${review?'복습':'집중학습'} 목표</h3><p><b>${target}문항</b> · ${done}문항 완료 · ${Math.max(0,target-done)}문항 남음</p><p>${review?'완료한 범위를 다시 학습합니다. 기존 Daily 완료 기록은 유지됩니다.':`이 Daily의 미학습 문항은 ${remainingDailyQuestions(d).length}개입니다. 목표가 남으면 다음 Daily로 이어집니다.`}</p><p>오답 회복은 집중학습 전용 문제군 안에서 추가됩니다. 즉시 재출제는 문항당 1회까지입니다.</p><button class="tool-btn" data-open-planner>다음 회차 분량 조정</button></section><section class="card"><h3>학습 근거 범위</h3><ul>${d.ranges.slice(0,8).map(r=>`<li>${esc(r)}</li>`).join('')}</ul><button class="wide" data-start="${d.id}">${resume?'이어서 학습':review?'완료 기록 유지하고 복습':'집중학습 시작'}</button></section></div>`,'learn');
}
function reviewListHtml(){const entries=reviewEntries().filter(e=>e.status!=='MASTERED').sort((a,b)=>String(a.dueOn).localeCompare(String(b.dueOn)));return `<section class="learn-card"><h3>취약 개념 목록</h3>${entries.length?entries.map(e=>{const c=CONCEPTS.find(c=>c.id===e.concept),ids=conceptQids(e.concept),quick=ids.some(id=>QUICK_SET.has(id));return `<div class="review-entry"><b>${esc(c?.name||e.concept)}</b><p>${esc(e.dueOn)} · ${quick?'5분 문제 회복 가능':'해당 Daily의 집중학습에서 회복'} · 누적 오답 ${e.wrongCount||0}회${ids.length<2?' · 대체문항 보강 필요':''}</p></div>`;}).join(''):'<p>현재 등록된 취약 개념이 없습니다.</p>'}</section>`;}
function bind(){
 const on=(s,fn)=>document.querySelectorAll(s).forEach(el=>el.onclick=()=>fn(el));
 on('[data-nav]',el=>{state.view=el.dataset.nav;save();render();});on('[data-back]',()=>{state.view=['quick','dailyIntro','learn','dailyEnd','sessionEnd','map','planner'].includes(state.view)?'learnHub':'home';save();render();});
 on('[data-start-quick]',()=>startQuick(false,state.focusGate?.pendingDailyId||nextDaily()?.id));on('[data-additional]',()=>{state.focusRun=null;startQuick(true,nextDaily()?.id);});
 on('[data-repair-quick]',()=>{state.quick=null;state.focusGate.ready=false;startQuick(true,state.focusGate.pendingDailyId||nextDaily()?.id);});
 on('[data-quick-pick]',el=>answerQuick(Number(el.dataset.quickPick)));on('[data-quick-detail]',el=>{if(state.quick){state.quick.detail=el.dataset.quickDetail;save();render();}});on('[data-quick-next]',nextQuick);
 on('[data-focus-daily]',el=>requestFocus(el.dataset.focusDaily));on('[data-daily]',el=>requestFocus(el.dataset.daily));on('[data-start]',el=>startDaily(el.dataset.start));on('[data-pick]',el=>answerLearn(Number(el.dataset.pick)));on('[data-rate]',el=>rateLearn(el.dataset.rate));
 on('[data-open-planner]',()=>{state.view='planner';save();render();});on('[data-plan-mode]',el=>{const mode=el.dataset.planMode,val=el.dataset.planValue;state.settings.mode=mode;if(mode==='time')state.settings.minutes=integer(val,40,160,DEFAULT_FOCUS_MINUTES);else state.settings.count=val==='all'?'all':integer(val,20,80,DEFAULT_FOCUS_COUNT);save();render();});on('[data-plan-reset]',()=>{state.settings={...DEFAULT_SETTINGS};save();render();});
 on('[data-mock-pick]',el=>{const pick=Number(el.dataset.mockPick);if(state.mock&&!state.mock.submitted&&validPick(pick)){state.mock.answers[state.mock.index]=pick;save();render();}});on('[data-mock-next]',advanceMock);on('[data-mock-prev]',()=>{if(state.mock&&!state.mock.submitted){state.mock.index=Math.max(0,state.mock.index-1);save();render();}});on('[data-review-next]',()=>{if(state.mock?.submitted){state.mock.reviewIndex++;if(state.mock.reviewIndex>=MOCK.length)state.mock.reviewDone=true;save();render();}});on('[data-mock-retry]',()=>{state.mock=null;save();render();});
 on('[data-export]',exportProgress);on('[data-export-recovery]',exportRecovery);on('[data-import]',()=>$('#importFile')?.click());const input=$('#importFile');if(input)input.onchange=importProgress;on('[data-reset]',resetProgress);on('[data-load-latest]',loadLatestProgress);
 document.querySelectorAll('[data-daily].map-row').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();requestFocus(el.dataset.daily);}};});
}
function render(){
 ensureStudyDay();const oldMain=$('.main'),scroll=oldMain?.scrollTop||0,pageScroll=window.scrollY;
 const key=[state.view,state.activeDaily,state.view==='quick'?state.quick?.index:state.view==='learn'?state.daily[state.activeDaily]?.index:state.view==='mock'?`${state.mock?.index}/${state.mock?.reviewIndex}/${state.mock?.submitted}`:''].join('|');let html;
 try{switch(state.view){case'home':html=state.focusRun&&!state.focusRun.active&&state.focusRun.done>=state.focusRun.target?completedHomeView():homeView();break;case'learnHub':html=learnHubView();break;case'quick':html=quickView();break;case'dailyIntro':html=dailyIntroView(state.activeDaily);break;case'learn':html=learnView();break;case'dailyEnd':html=dailyEndView();break;case'sessionEnd':html=sessionEndView();break;case'map':html=mapView();break;case'planner':html=plannerView();break;case'mock':html=mockView();break;case'tools':html=toolsView();break;default:html=homeView();}}
 catch(error){storageState.runtimeError=String(error);html=shell(`<div class="learn-hub"><section class="learn-card"><h2>화면을 불러오지 못했습니다.</h2><p>기록은 삭제하지 않았습니다. 먼저 내보내기로 보관해 주세요.</p><button data-export>기록 내보내기</button><button data-nav="home">홈으로</button></section></div>`);}
 document.getElementById('app').innerHTML=html;const main=$('.main');if(main){main.insertAdjacentHTML('afterbegin',storageBanner());main.scrollTop=lastScreenKey===key?scroll:0;}window.scrollTo(0,lastScreenKey===key?pageScroll:0);lastScreenKey=key;bind();
}
